### ISSUE TITLE
How to build a documentation badge without ReadTheDocs?

### ISSUE THREAD

**Issue by EvanBianco** [agile-geoscience/snowfake#14]
The badge in the README for documentation that was previously being generated by ReadTheDocs is no longer working because we are using our own URL. So we need to figure out how to create a badge a different way. I think. 

The badge does link to the current URL however, so at least folks will be redirected to the correct place.

**Comment by kwinkunks** [comment]
Go to *Create status badge* on the Action: 

![image](https://user-images.githubusercontent.com/1692372/153029939-75a75c3b-c5b7-443b-aa91-4bbefcc88eb1.png)

**Comment by EvanBianco** [comment]
Great. Noted! Closing.
